apiVersion: v1
kind: Secret
metadata:
  name: rancher-cluster
  namespace: argocd
  labels:
    # This label tells Argo CD: "This secret is a cluster destination"
    argocd.argoproj.io/secret-type: cluster
    argocd.argoproj.io/cluster-name: rancher
type: Opaque
stringData:
  name: rancher
  server: https://kubernetes.default.svc
  config: |
    {
      "tlsClientConfig": {
        "insecure": true
      }
    }